CREATE DATABASE zach;

\c zach

CREATE TABLE users
     (ID SERIAL PRIMARY KEY,
      NAME TEXT NOT NULL);

CREATE TABLE customers
     (ID SERIAL PRIMARY KEY,
      NUMBER TEXT NOT NULL,
      POSITIVE TEXT,
      NEGATIVE TEXT,
      RESPONSE TEXT DEFAULT NULL
    );

CREATE TABLE sms
    (ID  SERIAL PRIMARY KEY,
    TYPE INT NOT NULL,
    TEXT TEXT NOT NULL,
    USER_ID INT NOT NULL);


